spring:
  application:
    name: microservice2
  
#name: microservice2
---
spring:
  profile: local
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka